### ISSUE TITLE
Latest version of callsite breaks console-trace

### ISSUE THREAD

**Issue by dgem** [LearnBoost/console-trace#14]
Just setup a new node install and npm installed. It fails on the first log, for example:

``` javascript
console.log("bla");
```

results in a barf

``` javascript
DEBUG: Starting child process with 'node single.js'
domain.js:66
    throw er;
          ^
ReferenceError: __stack is not defined
    at Object.forEach.console.(anonymous function) [as info] (/Users/dan/code/server/node_modules/console-trace/console-trace.js:43:42)
    at Object.init (/Users/dan/code/server/lib/data_store.js:17:10)
    at Object.start (/Users/dan/code/server/lib/server.js:17:14)
    at Object.<anonymous> (/Users/dan/code/server/single.js:10:8)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
DEBUG: Program node single.js exited with code 1
```

It looks to me that it's because, 6 days ago, this commit in callsite - https://github.com/visionmedia/callsite/commit/4882cd047cbc234df1d07cfe26f618ecb1a45e5e removed the __stack var

Easiest fix looks like to set the callsite dependency to 0.0.1

**Comment by numbcoder** [comment]
I have send a pull request to fix this bug.
https://github.com/LearnBoost/console-trace/pull/17

**Comment by addlistener** [comment]
Is this package still maintained? Yarn install gives me 0.2.1 not 0.2.2
