### ISSUE TITLE
__stack not defined

### ISSUE THREAD

**Issue by jgentes** [LearnBoost/console-trace#21]
Just installed this with Node.js 0.10.x / Express 4.8.5 and I'm seeing this error when it runs into the first console.log statement:
'''
Starting child process with 'node server.js'

/home/ubuntu/workspace/node_modules/console-trace/console-trace.js:43
      arguments[0] = console.traceFormat(__stack[1], name) + pad + arguments[0
                                         ^
ReferenceError: __stack is not defined
    at Console.console.(anonymous function) [as log](/home/ubuntu/workspace/node_modules/console-trace/console-trace.js:43:42)
    at Object.<anonymous> (/home/ubuntu/workspace/server.js:51:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Program node server.js exited with code 8
'''

**Comment by jgentes** [comment]
I'm also using Morgan, although I disabled it and had the same error.

**Comment by jgentes** [comment]
Ah, this is apparently deprecated.. https://www.npmjs.org/package/debug-trace works great.
