### ISSUE TITLE
missing console.trace() support

### ISSUE THREAD

**Issue by kilianc** [LearnBoost/console-trace#3]
https://github.com/joyent/node/blob/master/lib/events.js#L140

```
[events.js:135] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Property 'trace' of object #<Object> is not a function
    at Socket.<anonymous> (events.js:139:15)
    at Socket.once (events.js:160:8)
    at Socket.setTimeout (net.js:142:12)
    at ClientRequest.<anonymous> (http.js:1284:29)
    at ClientRequest.g (events.js:156:14)
    at ClientRequest.emit (events.js:88:20)
    at Array.1 (http.js:1270:9)
    at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by martindale** [comment]
I'm affected by this as well, not so nice when a warning crashes the server. :(
